export const WORD_LENGTH = 5
export const MAX_GUESSES = 6

// Curated daily answers — common, recognizable 5-letter words
export const ANSWERS: readonly string[] = [
  'about', 'above', 'abuse', 'adult', 'after', 'again', 'agent', 'agree',
  'ahead', 'aisle', 'alike', 'alive', 'alley', 'allow', 'alone', 'along',
  'alter', 'angel', 'angle', 'ankle', 'apple', 'apply', 'arena', 'argue',
  'arise', 'armor', 'arose', 'array', 'arrow', 'aside', 'asset', 'avoid',
  'awake', 'award', 'aware', 'bacon', 'baker', 'beach', 'belly', 'bench',
  'birth', 'black', 'blame', 'blank', 'blast', 'blaze', 'bleed', 'bless',
  'blind', 'bliss', 'block', 'blood', 'bloom', 'blown', 'blues', 'blunt',
  'board', 'boast', 'bonus', 'boost', 'boots', 'bound', 'boxer', 'brave',
  'bread', 'break', 'breed', 'brick', 'bride', 'brief', 'bring', 'broke',
  'brook', 'broom', 'brown', 'brush', 'brute', 'buddy', 'build', 'built',
  'bunch', 'burst', 'buyer', 'cabin', 'candy', 'cargo', 'carry', 'catch',
  'cause', 'cedar', 'chain', 'chair', 'chalk', 'chaos', 'charm', 'chase',
  'cheap', 'cheat', 'check', 'cheek', 'cheer', 'chess', 'chest', 'chief',
  'child', 'choir', 'chunk', 'civic', 'civil', 'claim', 'clash', 'class',
  'clean', 'clear', 'clerk', 'click', 'cliff', 'climb', 'cling', 'cloak',
  'clock', 'clone', 'close', 'cloth', 'cloud', 'clown', 'coach', 'coast',
  'comet', 'coral', 'could', 'count', 'court', 'cover', 'craft', 'crane',
  'crash', 'crawl', 'crazy', 'cream', 'creek', 'creep', 'crime', 'crisp',
  'cross', 'crowd', 'crown', 'crush', 'curve', 'daddy', 'daisy', 'dance',
  'death', 'decay', 'delay', 'delta', 'depth', 'devil', 'dirty', 'disco',
  'diver', 'dodge', 'donor', 'dough', 'draft', 'drain', 'drama', 'dream',
  'dress', 'drift', 'drink', 'drive', 'drone', 'drops', 'drown', 'dozen',
  'eagle', 'early', 'earth', 'eight', 'elbow', 'elite', 'empty', 'enemy',
  'enjoy', 'enter', 'equal', 'error', 'essay', 'evade', 'event', 'exact',
  'exist', 'extra', 'fable', 'faith', 'false', 'fancy', 'fatal', 'fault',
  'feast', 'fence', 'ferry', 'fetch', 'fever', 'fiber', 'field', 'fifth',
  'fifty', 'final', 'first', 'fixed', 'flame', 'flash', 'flesh', 'float',
  'flood', 'floor', 'flour', 'fluid', 'flute', 'focus', 'forge', 'forum',
  'found', 'frame', 'frank', 'fraud', 'fresh', 'front', 'frost', 'fruit',
  'funny', 'fuzzy', 'ghost', 'giant', 'given', 'glare', 'glass', 'glaze',
  'gleam', 'glide', 'globe', 'gloom', 'glove', 'grace', 'grade', 'grain',
  'grant', 'graph', 'grasp', 'grass', 'grate', 'grave', 'graze', 'greed',
  'green', 'greet', 'grief', 'grill', 'grind', 'groan', 'gross', 'grove',
  'growl', 'grown', 'guard', 'guess', 'guise', 'habit', 'happy', 'harsh',
  'haunt', 'haven', 'havoc', 'heart', 'heavy', 'hedge', 'hinge', 'honor',
  'horse', 'hotel', 'hound', 'house', 'humor', 'hurry', 'ideal', 'image',
  'imply', 'inner', 'input', 'irony', 'issue', 'ivory', 'jelly', 'judge',
  'juice', 'juicy', 'jumbo', 'karma', 'knack', 'knife', 'knock', 'known',
  'labor', 'lance', 'large', 'laser', 'later', 'laugh', 'layer', 'learn',
  'lease', 'leave', 'legal', 'lemon', 'level', 'light', 'limit', 'liner',
  'local', 'lodge', 'logic', 'loose', 'lover', 'lower', 'lucky', 'lunch',
  'magic', 'major', 'manor', 'maple', 'march', 'match', 'mayor', 'mercy',
  'merit', 'metal', 'might', 'minor', 'model', 'money', 'month', 'moral',
  'motif', 'motor', 'mount', 'mourn', 'mouse', 'movie', 'music', 'naval',
  'niche', 'night', 'noble', 'noise', 'north', 'novel', 'nudge', 'nurse',
  'oasis', 'ocean', 'offer', 'opera', 'orbit', 'order', 'other', 'outer',
  'owner', 'ozone', 'panic', 'paper', 'party', 'pasta', 'patch', 'pause',
  'peace', 'peach', 'perch', 'peril', 'petal', 'phase', 'phone', 'photo',
  'piano', 'pitch', 'pixel', 'place', 'plane', 'plant', 'plaza', 'pluck',
  'plumb', 'plume', 'plump', 'poach', 'point', 'pound', 'power', 'prank',
  'press', 'price', 'pride', 'prime', 'print', 'prize', 'probe', 'prove',
  'prowl', 'pulse', 'punch', 'pupil', 'queen', 'query', 'quick', 'quiet',
  'quota', 'quote', 'radar', 'radio', 'rainy', 'raise', 'rally', 'ranch',
  'range', 'rapid', 'ratio', 'reach', 'rebel', 'reign', 'relax', 'realm',
  'reply', 'rider', 'ridge', 'right', 'risky', 'rival', 'river', 'rivet',
  'roast', 'robot', 'rough', 'round', 'rover', 'rowdy', 'ruler', 'rusty',
  'saint', 'salad', 'sauce', 'scalp', 'scare', 'scene', 'scope', 'score',
  'scout', 'scrap', 'seize', 'sense', 'serum', 'seven', 'shade', 'shaft',
  'shake', 'shame', 'shape', 'share', 'shark', 'sharp', 'sheep', 'sheen',
  'sheet', 'shelf', 'shell', 'shift', 'shine', 'shirt', 'shock', 'shore',
  'short', 'shout', 'shove', 'siege', 'sight', 'silky', 'sixth', 'sixty',
  'skill', 'skull', 'slate', 'slave', 'sleek', 'slice', 'slide', 'slope',
  'sloth', 'slump', 'smart', 'smash', 'smell', 'smile', 'smoke', 'snack',
  'snail', 'snake', 'snare', 'sneak', 'snore', 'solar', 'solve', 'sorry',
  'south', 'spade', 'spare', 'spark', 'spear', 'speed', 'spend', 'spill',
  'spine', 'spook', 'spoon', 'sport', 'spray', 'spree', 'squad', 'squat',
  'stain', 'stale', 'stall', 'stamp', 'stand', 'stare', 'stark', 'start',
  'steal', 'steel', 'steep', 'steer', 'stern', 'stiff', 'still', 'sting',
  'stink', 'stock', 'store', 'storm', 'stout', 'strap', 'straw', 'stray',
  'stuck', 'study', 'stump', 'style', 'sugar', 'suite', 'sunny', 'super',
  'surge', 'swamp', 'swear', 'sweat', 'sweep', 'sweet', 'swift', 'swing',
  'swipe', 'swirl', 'swoop', 'sword', 'syrup', 'table', 'taunt', 'teach',
  'teeth', 'tense', 'thank', 'theme', 'there', 'thick', 'thing', 'think',
  'third', 'thorn', 'three', 'threw', 'throw', 'thumb', 'tiger', 'tight',
  'timer', 'tired', 'title', 'toast', 'token', 'topic', 'touch', 'tough',
  'towel', 'tower', 'trace', 'track', 'trade', 'trail', 'train', 'trait',
  'trend', 'trial', 'tribe', 'trick', 'tried', 'troll', 'troop', 'trove',
  'truce', 'truly', 'tryst', 'tulip', 'tumor', 'tweak', 'twirl', 'twist',
  'ultra', 'uncle', 'under', 'unify', 'union', 'unite', 'unity', 'upper',
  'upset', 'urban', 'usage', 'usher', 'utter', 'vague', 'value', 'valve',
  'vapor', 'vault', 'verse', 'vigor', 'viola', 'viper', 'vital', 'vivid',
  'vocal', 'voter', 'wafer', 'waltz', 'waste', 'watch', 'water', 'weary',
  'weave', 'wedge', 'weird', 'whale', 'wheat', 'wheel', 'where', 'while',
  'whole', 'whose', 'world', 'worry', 'worth', 'would', 'wound', 'wrath',
  'wreck', 'wring', 'yacht', 'yield', 'young', 'youth', 'zebra',
]

// Additional valid guesses that are not answer candidates
const EXTRA_GUESSES: readonly string[] = [
  'abbot', 'abhor', 'abide', 'abode', 'abort', 'acorn', 'acrid', 'adage',
  'adept', 'adorn', 'aegis', 'afoot', 'aglow', 'agony', 'album', 'algae',
  'alibi', 'align', 'aloft', 'aloof', 'altar', 'amass', 'amaze', 'amend',
  'amiss', 'ample', 'annex', 'antic', 'aptly', 'ardor', 'askew', 'atlas',
  'attic', 'audit', 'augur', 'avail', 'avert', 'balmy', 'banal', 'baron',
  'basic', 'batch', 'bland', 'blare', 'bleat', 'blimp', 'bloat', 'bloke',
  'blurb', 'blurt', 'bogus', 'brash', 'bravo', 'brawn', 'braze', 'brine',
  'broil', 'brood', 'cache', 'cadet', 'camel', 'canoe', 'caper', 'carol',
  'carve', 'cavil', 'chafe', 'chant', 'chide', 'chive', 'chord', 'chore',
  'chose', 'churn', 'cider', 'clasp', 'clomp', 'clout', 'clump', 'colon',
  'combo', 'conch', 'corny', 'couch', 'cough', 'covet', 'cramp', 'crave',
  'creak', 'creed', 'crimp', 'crook', 'croup', 'crust', 'cubic', 'curry',
  'cynic', 'daunt', 'delve', 'depot', 'derby', 'ditty', 'divvy', 'dizzy',
  'dolly', 'dopey', 'dowdy', 'dowry', 'droll', 'droop', 'drupe', 'dully',
  'dumpy', 'dunce', 'dusky', 'dusty', 'dwarf', 'eerie', 'egret', 'embed',
  'emcee', 'emote', 'enact', 'endow', 'envoy', 'expel', 'extol', 'exult',
  'flair', 'flank', 'flare', 'flask', 'flaunt', 'flaw', 'flick', 'fling',
  'flint', 'flock', 'floss', 'flout', 'flown', 'fluke', 'flung', 'flunk',
  'foray', 'forte', 'frail', 'freak', 'froth', 'froze', 'fudge', 'fugue',
  'gaudy', 'gauze', 'gavel', 'gaudy', 'gecko', 'girth', 'glint', 'gloat',
  'gloomy', 'gloss', 'glower', 'glyph', 'gnash', 'gnome', 'golem', 'gorge',
  'gouge', 'gourd', 'grimy', 'gripe', 'groan', 'grope', 'grout', 'gruff',
  'grump', 'grunge', 'guile', 'gusto', 'gypsy', 'haiku', 'hairy', 'handy',
  'hasty', 'haste', 'hazel', 'heady', 'heist', 'herby', 'heron', 'hippo',
  'hitch', 'hoary', 'hoist', 'homey', 'hooky', 'hotly', 'husky', 'hyena',
  'hyper', 'inbox', 'inept', 'inert', 'infer', 'inter', 'intro', 'jaunt',
  'jazzy', 'jewel', 'jumpy', 'keyed', 'kinky', 'kneel', 'knelt', 'knoll',
  'koala', 'lanky', 'lapel', 'lathe', 'latte', 'leapt', 'lefty', 'lemur',
  'lithe', 'livid', 'llama', 'loopy', 'lowly', 'lucid', 'lumpy', 'lusty',
  'lyric', 'mangy', 'manor', 'maxim', 'melee', 'melon', 'mercy', 'messy',
  'mirth', 'miser', 'mitre', 'moist', 'moldy', 'moody', 'mossy', 'motto',
  'muddy', 'mulch', 'murky', 'musty', 'naive', 'nervy', 'niece', 'nifty',
  'nimble', 'nippy', 'nymph', 'occur', 'offal', 'often', 'onset', 'optic',
  'ovoid', 'paddy', 'panda', 'panel', 'patsy', 'pawns', 'peeve', 'peppy',
  'perky', 'petty', 'picky', 'piggy', 'pique', 'pithy', 'piton', 'plaid',
  'plead', 'pleat', 'plonk', 'plotz', 'pluck', 'plunk', 'plush', 'posse',
  'pouty', 'prawn', 'primp', 'prior', 'privy', 'prude', 'prune', 'psalm',
  'pubic', 'pudgy', 'punky', 'pygmy', 'rabbi', 'rabid', 'ramen', 'randy',
  'rapid', 'raspy', 'ratty', 'recap', 'reedy', 'remix', 'renew', 'repay',
  'repel', 'rerun', 'retch', 'retro', 'revel', 'rocky', 'rouge', 'rouse',
  'rowel', 'ruddy', 'rugby', 'rummy', 'runny', 'rupee', 'sabre', 'sadly',
  'saggy', 'sassy', 'saucy', 'savvy', 'scald', 'scant', 'scoff', 'scone',
  'scoop', 'scour', 'scowl', 'scram', 'screw', 'scrub', 'seedy', 'septic',
  'shack', 'shaky', 'shawl', 'shrug', 'sigma', 'silly', 'siren', 'skimp',
  'skivy', 'slimy', 'slink', 'sloop', 'slosh', 'sloth', 'slurp', 'smelt',
  'smirk', 'smite', 'smock', 'smolt', 'sniff', 'snort', 'snuck', 'snuff',
  'sooty', 'soppy', 'spank', 'spawn', 'speck', 'sprig', 'squid', 'stank',
  'stays', 'stems', 'stomp', 'stooge', 'strum', 'stung', 'stunk', 'stunt',
  'suave', 'suede', 'sulky', 'surly', 'swill', 'tacky', 'taffy', 'tardy',
  'tatty', 'tawny', 'tepid', 'terse', 'testy', 'thane', 'thatch', 'throe',
  'timid', 'tipsy', 'toady', 'toddy', 'tonic', 'torso', 'totem', 'toxic',
  'tramp', 'trashy', 'trawl', 'tripe', 'trite', 'troth', 'tubby', 'tuner',
  'tunic', 'tweed', 'udder', 'unfit', 'unzip', 'upend', 'usurp', 'venom',
  'vicar', 'visor', 'vista', 'vixen', 'vodka', 'voila', 'vouch', 'vowel',
  'wacky', 'wader', 'wafty', 'waged', 'waken', 'wanly', 'warty', 'waver',
  'weedy', 'welts', 'whiff', 'whirl', 'whisk', 'wimpy', 'windy', 'witty',
  'woken', 'wordy', 'wreak', 'wrest', 'wrote', 'yearn', 'zappy', 'zesty',
  'zilch', 'zippy', 'zombi', 'adieu', 'audio',
]

export const VALID_GUESSES: Set<string> = new Set([...ANSWERS, ...EXTRA_GUESSES])

export function getTodaysAnswer(): string {
  const epoch = new Date('2025-01-01').getTime()
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  const dayIndex = Math.floor((today.getTime() - epoch) / 86_400_000)
  return ANSWERS[Math.abs(dayIndex) % ANSWERS.length]
}
